### ISSUE TITLE
Switches not working in 2024.1.5

### ISSUE THREAD

**Issue by colinjgibbs** [hardbyte/ha-evnex#27]
So, I installed the new entity.py (committed on the 19th Jan) in the evnex custom component directory.  I then upgraded HA Core to the latest 2024.1.5.  Evnex now loads but there is an issue with the switches, (log entry below).  Have I missed a dependancy? Does it need more than just the entity module?

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:360
Integration: Switch (documentation, issues)
First occurred: 13:56:48 (1 occurrences)
Last logged: 13:56:48

Error while setting up evnex platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/evnex/switch.py", line 139, in async_setup_entry
    EvnexChargerAvailabilitySwitch(
  File "/config/custom_components/evnex/switch.py", line 72, in __init__
    super().__init__(
  File "/config/custom_components/evnex/entity.py", line 107, in __init__
    super().__init__(coordinator, charger_id=charger_id)
  File "/config/custom_components/evnex/entity.py", line 73, in __init__
    self._attr_unique_id = self.charger_id + self.entity_description.key
                                             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EvnexChargerAvailabilitySwitch' object has no attribute 'entity_description'

**Comment by drc38** [comment]
In `switch.py` line 76 needs to be moved to line 71 and slightly amended I think based on your log:
```
self.entity_description = SwitchEntityDescription(
            key="_".join(["connector", connector_id, "availability_switch"]),
            name=f"Connector {connector_id} Availability",
        )
```

**Comment by colinjgibbs** [comment]
Thanks for the fast reply. I have tried what you suggest - here is the relevant modified section from switch.py now:

`class EvnexChargerAvailabilitySwitch(EvnexChargePointConnectorEntity, SwitchEntity):
    def __init__(self, api_client, coordinator, charger_id, connector_id="1"):
        """Initialise the switch."""
        self.evnex: Evnex = api_client

		self.entity_description = SwitchEntityDescription(
            key="_".join(["connector", connector_id, "availability_switch"]),
            name=f"Connector {connector_id} Availability",
        )
        
        super().__init__(
            coordinator=coordinator, charger_id=charger_id, connector_id=connector_id
        )

  `
This gives in the log:
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:360
Integration: Switch (documentation, issues)
First occurred: 21 January 2024 at 13:56:48 (2 occurrences)
Last logged: 09:20:49

Error while setting up evnex platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/evnex/switch.py", line 139, in async_setup_entry
    EvnexChargerAvailabilitySwitch(
  File "/config/custom_components/evnex/switch.py", line 72, in __init__
    super().__init__(
  File "/config/custom_components/evnex/entity.py", line 107, in __init__
    super().__init__(coordinator, charger_id=charger_id)
  File "/config/custom_components/evnex/entity.py", line 73, in __init__
    self._attr_unique_id = self.charger_id + self.entity_description.key
                                             ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EvnexChargerAvailabilitySwitch' object has no attribute 'entity_description'

**Comment by drc38** [comment]
Hmm, it may need `entity_description: SwitchEntityDescription` just after the class definition line 67 and before the `__init__` definition but I'm unsure why as the `entity_description` should be inherited from the `SwitchEntity` class

**Comment by colinjgibbs** [comment]
Hmm, still no joy. Exactly the same error in the log.
AttributeError: 'EvnexChargerAvailabilitySwitch' object has no attribute 'entity_description'

**Comment by drc38** [comment]
@hardbyte any ideas as to why the error?

**Comment by colinjgibbs** [comment]
Just to recap, it worked fine in 2024.1.3. It stopped working when I upgraded to 2024.1.5 and used the new entity.py file for evnex (which fixed the entity issue which came with 2024.1.4). Unfortunately I did both at the same time. I could regress to 2024.1.3 to see if it works, but would that be OK with the new entity.py file?
